language: php

php:
 - 7.1
 - 7.2

before_script:
 - composer install --no-interaction
 - mkdir -p build/logs
script:
 - composer cs-check
 - composer phpstan
 - ./vendor/bin/composer-require-checker
 - ./vendor/bin/phpunit

after_script:
 - php vendor/bin/coveralls -v
